version: '3'

services:

  postgres:
    image: postgres:11.0
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test_postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd123